### ISSUE TITLE
Symfony form information

### ISSUE THREAD

**Issue by yceruto** [Nyholm/symfony-bootstrap-form#4]
Hi Tobias,

Congratulations for this great initiative, I really like the practical effect it provides, thanks.

Some time ago I've been thinking about doing something like that, but showing the internal information of Symfony forms. Basically keep this information up to date as you have done here with form's themes:

 * http://symfony.com/doc/current/forms.html#built-in-field-types
 * http://symfony.com/doc/current/reference/forms/types/choice.html

Also, showing some lost information like type extensions availables, type guessers 
and the field options that aren't shown in the doc.

For example, you could use the `debug:form --format=json` command to get general information,`debug:form ChoiceType --format=json` to get the predefined options, parent types, type extensions, etc. and `debug:form ChoiceType data_class --format=json` to get the predefined information of such option and so on. It would be nice to even be able to select other versions of Symfony or at least the LTS and current one.

This command is available since 3.4 but is possible adapt it to oldest Symfony versions. See implementation details:
* https://github.com/symfony/symfony/pull/24185 (`debug:form`)
* https://github.com/symfony/symfony/pull/23694 (`debug:form <Type>`)
* https://github.com/symfony/symfony/pull/24208 (`debug:form <Type> <option>`)

Let me know if it is of your interest, I could help you implement the idea.

Greetings.

**Comment by Nyholm** [comment]
Thank you. 

Great suggestions. I will continue to work on this. 
Thanks!

**Comment by yceruto** [comment]
Well, I can't do it automatically like you :(, but at least I can generate this static information for each release.

See https://phptopup.github.io/symfony-form/index.html !! any feedback is welcomed! ;)
